language: csharp
solution: Sendgrid.Webhooks.sln
install:
  - nuget restore Sendgrid.Webhooks.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe